---
title: _Anheteromeyenia argyrosperma_
output: html_document
---
  
<style type="text/css">
h1.title {
  font-size: 40px;
  text-align: center;
}
body {
background-color: #B9F2FE
}
</style>
<br>
<br>
  
While _A. argyrosperma_ was located in Dr. Poirrier's Louisiana survey in 1968, but
it has not been located in this current survey. 

<br>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.keep='none'}
library(tidyverse)
library(sf)
library(rgdal)
library(sp)
library(readxl)
library(ggspatial)
library(ggmap)
library(RColorBrewer)
```

```{r echo=FALSE, results='hide', message=FALSE, warning=FALSE}
states<-st_read("/Users/abhimehrotra/Desktop/Sponge Hunters Webpage/states")
la.b<-st_crop(states,xmin=-94.15,xmax=-89,ymin=29,ymax=33.15)
la.c<-states[states$STATE_NAME=="Louisiana",]
sites<-read_xlsx("/Users/abhimehrotra/Desktop/Sponge Hunters Webpage/Miller_sponge gps coordinates_summer 2021.xlsx", sheet="Aa")
```

```{r map, echo=FALSE, fig.align='center', fig.asp=.95}
(map1<-ggplot()+
    geom_sf(data=la.c)+
    geom_point(aes(x=Long,y=Lat, color=Aa),data=sites,size=3)+
    scale_color_brewer(palette = "Dark2",name="Anheteromeyenia argyrosperma")+
    ylab("Latitude")+
    xlab("Longitude")+
    theme_set(theme_bw())+
    theme(panel.grid = element_blank())+
    theme(legend.position="none")+
    theme(axis.text = element_text(size=10,family="sans"),
          axis.title= element_text(size=12,family="sans")))
```
